// <auto-generated />
using System;
using DemoTruongDuLieuDong.Data.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DemoTruongDuLieuDong.Migrations
{
    [DbContext(typeof(DemoTruongDuLieuDongDbContext))]
    [Migration("20201130041329_Init_Project")]
    partial class Init_Project
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("DemoTruongDuLieuDong.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<double?>("GiaBan")
                        .HasColumnType("double precision");

                    b.Property<double?>("GiaNhap")
                        .HasColumnType("double precision");

                    b.Property<string>("MaHangHoa")
                        .HasColumnType("text");

                    b.Property<string>("SoLuong")
                        .HasColumnType("text");

                    b.Property<string>("TenHangHoa")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DemoTruongDuLieuDong.Models.ProductField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("NoiDung")
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("TenTruong")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductFields");
                });
#pragma warning restore 612, 618
        }
    }
}
